"""environment.py

Reinforcement-learning based intrusion detection environment.

State vector (tabular Q-learning):
    [request_rate, failed_logins, unknown_ip, time_of_day]

Actions:
    0 = ALLOW
    1 = MONITOR
    2 = THROTTLE
    3 = BLOCK

Reward:
    Uses ground-truth intrusion heuristic + severity to shape rewards:
      - Missed attacks (should have escalated/block) are heavily penalized.
      - Suspicious traffic gets lower penalties if agent chooses MONITOR/THROTTLE.
      - False positives are penalized but less than missed attacks.

This environment consumes traffic records (dictionaries) generated by `simulator.py`.
"""

from __future__ import annotations

from typing import Any, Dict, List, Sequence, Tuple


Action = int
State = Tuple[int, int, int, int]


class IntrusionDetectionEnvironment:
    """Episodic environment over a fixed traffic stream."""

    # action mapping escalation order for reward shaping
    ACTION_ALLOW = 0
    ACTION_MONITOR = 1
    ACTION_THROTTLE = 2
    ACTION_BLOCK = 3

    def __init__(
        self,
        traffic_data: Sequence[Dict[str, int]] | None = None,
        *,
        simulator: object | None = None,
        n_samples: int = 1000,
        seed: int | None = 42,
        config: object | None = None,
    ) -> None:
        self.config = config

        if traffic_data is None:
            if simulator is None:
                raise ValueError("Either traffic_data or simulator must be provided")
            self.traffic_data: List[Dict[str, int]] = list(
                simulator.generate_traffic(n_samples, as_dataframe=False, seed=seed)
            )
        else:
            self.traffic_data = list(traffic_data)

        if not self.traffic_data:
            raise ValueError("traffic_data is empty")

        self._idx = 0

    @staticmethod
    def _record_to_state(record: Dict[str, int]) -> State:
        return (
            int(record["request_rate"]),
            int(record["failed_logins"]),
            int(record["unknown_ip"]),
            int(record["time_of_day"]),
        )

    @staticmethod
    def _severity_and_is_intrusion(record: Dict[str, int]) -> tuple[bool, int, str]:
        """Ground truth heuristic (used for rewards + metrics).

        Returns:
            (is_intrusion, severity_level_1_to_3, attack_type)
        """
        rr = int(record["request_rate"])
        fl = int(record["failed_logins"])
        ui = int(record["unknown_ip"])
        traffic_spike = int(record.get("traffic_spike", 0))
        repeated = int(record.get("repeated_requests", 0))
        session_duration = int(record.get("session_duration", 0))
        packet_size = int(record.get("packet_size", 0))
        ip_rep = int(record.get("ip_reputation_score", 50))

        # Attack-type inference from features (approximate)
        if fl >= 7 and repeated >= 15:
            attack_type = "credential_stuffing"
        elif fl >= 6 and repeated >= 10:
            attack_type = "brute_force"
        elif rr >= 80 and traffic_spike == 1:
            attack_type = "ddos"
        elif repeated >= 18 and rr >= 45 and packet_size <= 8:
            attack_type = "port_scan"
        elif rr >= 35 and fl <= 3 and ip_rep <= 35 and session_duration >= 200:
            attack_type = "bot_traffic"
        elif session_duration >= 500 and repeated >= 12 and ip_rep <= 55 and fl <= 4:
            attack_type = "insider_threat"
        elif ui == 1 and (rr >= 40 or repeated >= 10) and ip_rep >= 35:
            attack_type = "unknown_behavior"
        else:
            attack_type = "normal"


        # Severity score (1..3)
        # 3 = dangerous attack (should BLOCK)
        severity = 1
        is_intrusion = False

        # Dangerous rules
        if attack_type in {"ddos", "credential_stuffing"}:
            if rr >= 75 or fl >= 7 or traffic_spike == 1:
                severity = 3
                is_intrusion = True
        if attack_type in {"brute_force", "bot_traffic", "port_scan"}:
            if fl >= 5 or rr >= 55 or repeated >= 18:
                severity = 2 if (ip_rep >= 20 and traffic_spike == 0) else 3
                is_intrusion = True
        if attack_type == "insider_threat":
            # Insider behavior is often suspicious but can be less overt than volumetric attacks.
            if session_duration >= 550 or repeated >= 16:
                severity = 2
                is_intrusion = True
            if traffic_spike == 1 or ip_rep <= 30:
                severity = 3
                is_intrusion = True

        if attack_type == "unknown_behavior":
            # suspicious but may be false positive
            if ui == 1 and (rr >= 50 or repeated >= 12):
                severity = 2
                is_intrusion = True

        # Normal baseline false intrusion rate kept low
        if attack_type == "normal":
            # extremely high volume with low rep still counts as intrusion
            if rr >= 90 and ip_rep <= 30 and traffic_spike == 1:
                is_intrusion = True
                severity = 3
            else:
                is_intrusion = False
                severity = 1

        return is_intrusion, severity, attack_type

    @staticmethod
    def _required_action(severity: int) -> int:
        """Ideal escalation for a given severity.

        1 = safe -> ALLOW
        2 = suspicious -> MONITOR/THROTTLE
        3 = dangerous -> BLOCK
        """
        if severity <= 1:
            return IntrusionDetectionEnvironment.ACTION_ALLOW
        if severity == 2:
            return IntrusionDetectionEnvironment.ACTION_THROTTLE
        return IntrusionDetectionEnvironment.ACTION_BLOCK

    def reset(self) -> State:
        self._idx = 0
        return self._record_to_state(self.traffic_data[self._idx])

    def step(self, action: Action) -> tuple[State, float, bool, dict]:
        if action not in (0, 1, 2, 3):
            raise ValueError("action must be 0 (ALLOW), 1 (MONITOR), 2 (THROTTLE), 3 (BLOCK)")

        if self._idx >= len(self.traffic_data):
            raise RuntimeError("step() called after episode ended; call reset()")

        record = self.traffic_data[self._idx]
        state = self._record_to_state(record)

        is_intrusion, severity, attack_type = self._severity_and_is_intrusion(record)

        # Reward shaping
        ideal = self._required_action(severity)

        # False positives: is intrusion? false when agent escalates on safe.
        false_positive = (not is_intrusion) and (action != self.ACTION_ALLOW)
        missed_attack = is_intrusion and (action < ideal)
        over_escalation = (not is_intrusion) and (action > self.ACTION_ALLOW)

        reward = 0.0

        if is_intrusion:
            # missed attacks are costly depending on severity
            if action == ideal:
                reward += 2.0 if severity == 3 else 1.0
            elif missed_attack:
                reward -= 6.0 if severity == 3 else 3.0
            else:
                # action > ideal (over-escalate): smaller penalty
                reward -= 1.0 if severity == 3 else 0.5
        else:
            # safe traffic: penalize unnecessary escalations but lightly
            if action == self.ACTION_ALLOW:
                reward += 1.5
            else:
                reward -= 1.0 if action == self.ACTION_MONITOR else 1.4

        # Additional bias: suspicious traffic shouldn't be over-penalized if MONITOR/THROTTLE chosen
        if (not is_intrusion) and severity == 1 and action == self.ACTION_MONITOR:
            reward += 0.2  # slight tolerance

        correct = (is_intrusion and action >= ideal) or ((not is_intrusion) and action == self.ACTION_ALLOW)

        self._idx += 1
        done = self._idx >= len(self.traffic_data)

        next_state = state if done else self._record_to_state(self.traffic_data[self._idx])

        info = {
            "is_intrusion": is_intrusion,
            "severity": severity,
            "attack_type": attack_type,
            "ideal_action": ideal,
            "correct": correct,
            "missed_attack": missed_attack,
            "false_positive": false_positive or over_escalation,
            "idx": self._idx,
            "taken_action": action,
        }

        return next_state, float(reward), done, info



